/*
This simple program calculates the x and y co-ordinates
of the ultrasonic transmitter relative to the centre of
the robot.  It uses a standalone feed forward neural net
generated by the Synaptic.JS library.

It captures the data from the five ultrasonic sensors
and uses the neural net to calculate three values between
zero and one.  These are then translated to the sine, cosine and
distance of the transmitter.

Simple trigonometry is then used to translate those values
to x and y co-ordinates.

Published under Creative Commons
Richard Hopkins, 8th October 2017
*/
function calculate(input) {  // this is the generated function
F = {
0: 0,
1: 0,
2: 0,
3: 0,
4: 0,
13: 0.6937412195263934,
5: 0.8179378052145558,
6: 0.817668576059859,
7: 0.8174579255066473,
8: 0.3988575542663343,
9: -2.5523729087161513,
10: 2.473237725929897,
11: -1.4843566153549508,
12: 1.3911138454035965,
14: 0.21246433985642582,
48: 2.305818996050941,
57: -1.4718553641561527,
66: -0.12611636533099285,
23: 0.8474472064647863,
15: 1.7148350785632773,
16: 1.7147178208027223,
17: 1.7146753901320397,
18: -5.019182810934683,
19: -5.030776636580335,
20: -1.4409648306343215,
21: -2.410388156801609,
22: 1.8074394754202079,
24: 0.12928043871981615,
49: 1.383812193036601,
58: -1.6609540299560315,
67: 0.6795672950534035,
33: 0.6656350493601403,
25: 0.6884134371453158,
26: 0.6885084833766109,
27: 0.6881365720993877,
28: 4.161556180523247,
29: 1.3854271988252573,
30: 1.2255595867369253,
31: -1.437354603300487,
32: -2.4076471340067287,
34: 0.2225650304234639,
50: 3.488295532133519,
59: 2.5042979288168628,
68: 0.6656277456642462,
43: 0.5960337292775467,
35: 0.3885659892850066,
36: 0.3889658720465543,
37: 0.38937902002943425,
38: -1.4240924845726803,
39: -3.2315403227365413,
40: -2.7422102904849828,
41: -2.258288523073314,
42: -4.231167110001925,
44: 0.24077752284104686,
51: -2.4314767178968313,
60: 0.9005471361219064,
69: 2.4432850581489203,
52: 0.48132341430725095,
45: -0.07367999431428385,
46: -0.07474111679622264,
47: -3.721187008107108,
53: 0.24965118514686144,
61: 0.47531885922238876,
54: -0.1003946305808191,
55: -0.09880486578084025,
56: 0.12589479563625547,
62: 0.24939084128991576,
70: 0.7336205871726438,
63: 1.0120249370046914,
64: 1.0130703272574735,
65: -1.3738818755122089,
71: 0.19542142124910916
};
F[0] = input[0];
F[1] = input[1];
F[2] = input[2];
F[3] = input[3];
F[4] = input[4];
F[5] = F[6];F[6] = F[7];F[6] += F[0] * F[8];F[6] += F[1] * F[9];F[6] += F[2] * F[10];F[6] += F[3] * F[11];F[6] += F[4] * F[12];F[13] = (1 / (1 + Math.exp(-F[6])));F[14] = F[13] * (1 - F[13]);
F[15] = F[16];F[16] = F[17];F[16] += F[0] * F[18];F[16] += F[1] * F[19];F[16] += F[2] * F[20];F[16] += F[3] * F[21];F[16] += F[4] * F[22];F[23] = (1 / (1 + Math.exp(-F[16])));F[24] = F[23] * (1 - F[23]);
F[25] = F[26];F[26] = F[27];F[26] += F[0] * F[28];F[26] += F[1] * F[29];F[26] += F[2] * F[30];F[26] += F[3] * F[31];F[26] += F[4] * F[32];F[33] = (1 / (1 + Math.exp(-F[26])));F[34] = F[33] * (1 - F[33]);
F[35] = F[36];F[36] = F[37];F[36] += F[0] * F[38];F[36] += F[1] * F[39];F[36] += F[2] * F[40];F[36] += F[3] * F[41];F[36] += F[4] * F[42];F[43] = (1 / (1 + Math.exp(-F[36])));F[44] = F[43] * (1 - F[43]);
F[45] = F[46];F[46] = F[47];F[46] += F[13] * F[48];F[46] += F[23] * F[49];F[46] += F[33] * F[50];F[46] += F[43] * F[51];F[52] = (1 / (1 + Math.exp(-F[46])));F[53] = F[52] * (1 - F[52]);
F[54] = F[55];F[55] = F[56];F[55] += F[13] * F[57];F[55] += F[23] * F[58];F[55] += F[33] * F[59];F[55] += F[43] * F[60];F[61] = (1 / (1 + Math.exp(-F[55])));F[62] = F[61] * (1 - F[61]);
F[63] = F[64];F[64] = F[65];F[64] += F[13] * F[66];F[64] += F[23] * F[67];F[64] += F[33] * F[68];F[64] += F[43] * F[69];F[70] = (1 / (1 + Math.exp(-F[64])));F[71] = F[70] * (1 - F[70]);
var output = [];
output[0] = F[52];
output[1] = F[61];
output[2] = F[70];
return output;
}
while (true)  // keep on taking readings
{
  // take readings from each of the five ultrasonic sensors
  front_left=digitalRead(A2);
  front_right=digitalRead(A3);
  left=digitalRead(A4);
  right=digitalRead(A5);
  back=digitalRead(A6);
  // if the sensors are all reading zero, no point
  // in calling the neural net
  if (front_left+front_right+left+right+back>0){
    // create the input array from the sensor readings
    input =[front_left,front_right,left,right,back];
    output=calculate(input); // call the neural net
    sine = 2*Math.PI*((2*output[0])-1);   // convert the 0-1 output_0 to sine value
    cosine = 2*Math.PI*((2*output[1])-1); // convert the 0-1 output_1 to cosine value
    distance = output[2]*1.5;  // convert the 0-1 output_2 to actual distance
    x = cosine * distance;  // calculate the x co-ordinate
    y = sine * distance; // calculate the y co-ordinate
    console.log("," + x + "," + y);  // output the x,y co-ordinates to the console
  }
}
