#!/bin/sh
# Stop the running K9 processes
node-red-stop
kill $(pgrep -f 'K9PythonController.py')
# Ensure that hidden files are copied
shopt -s dotglob nullglob
# Copy the node-RED flows to the home directory
sudo cp /var/lib/jenkins/jobs/k9/workspace/k9-chess-angular/node-RED/flows_k9.json /home/pi/.node-red/flows_k9.json
# Copy the remainder of the files to the Apache webserver
sudo cp -r /var/lib/jenkins/jobs/k9/workspace/k9-chess-angular/* /var/www/html
# Restart the running K9 processes
node-red-start &>> node-red.log
sleep 30
python /var/www/html/python/K9PythonController.py test &>> k9-controller.log
